### ISSUE TITLE
XML reference error

### ISSUE THREAD

**Issue by benmichel** [bpmn-miwg/bpmn-miwg-demos#12]
In yaoqiang-4.0 submission for Diagram interchange demo, we have a XML reference error : Unresolved reference '_18' line 91

```
<subProcess completionQuantity="1" id="_17" isForCompensation="false" startQuantity="1" triggeredByEvent="false">
  <incoming>_18</incoming>
</subProcess>
```

**Comment by tstephen** [comment]
Since this is in the export test I think what must have happened is that I created an extra unnecessary subprocess and the tool must have failed to remove it fully on delete. In any case neither the sub-proc nor the incoming element should have been there and I have removed them. I added a roundtrip test at the same time.
